stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy_job:
  stage: deploy
  image: appropriate/curl
  script:
    - 'curl --request POST --form "token=$DEPLOY_TOKEN" --form ref=master --form "variables[CUSTOM_ENV]=production" https://gitlab.example.com/api/v4/projects/123/deploy_trigger'
  only:
    - master
